#PBS -S /bin/bash
### General Options ###
#PBS -N CdS33_50-tddft
#PBS -V
### Resource Handling ###
#PBS -l nodes=1:ppn=25
#PBS -q GPU
#PBS -l walltime=80:00:00
### Output Stream Options ###
### Mail Options ###
#PBS -m bea
 
### Bash script ###
module load intel-mpi-7
module load cp2k-6.1
cd /home/99425001/step2_1/Project_Libra_CP2K/Cd33Se33/step2/cds50_2000-2200
python trajectory2energy.py

exit 0