#PBS -S /bin/bash
### General Options ###
#PBS -N CdS33-MD_50
#PBS -V
### Resource Handling ###
#PBS -l nodes=1:ppn=25
#PBS -q GPU
#PBS -l walltime=80:00:00
### Output Stream Options ###
### Mail Options ###
#PBS -m bea
 
### Bash script ###
module load intel-mpi-7
module load cp2k-6.1
cd /home/99425001/Desktop/CP2K_Libra_Manual/molecular_dynamics/cds33_50
  
mpirun -np 25 cp2k.psmp -i md.inp -o out-CdS33_MD_50.log



exit 0